branch_whitelist = [ "main", "release/**" ]
pre_bump_hooks = [
  "poetry version {{version}}"
]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "tbpore"
owner = "mbhall88"
authors = [
  { signature = "Michael Hall", username = "mbhall88" },
  { signature = "Leandro Lima", username = "leoisl" }
]